import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <nav className={`flex space-x-3 w-full px-10 bg-yellow-50 border-b border-gray-100`}>
        <Link className={`p-3`} href="/">Home</Link>
        <Link className={`p-3`} href="/planner">Planner</Link>
        <Link className={`p-3`} href="/help">Help</Link>
        <div className={`flex-grow`}/>
        <Link className={`p-3`} target={'_blank'}
              href="https://github.com/Inertia-Squared/subject-planner">Github</Link>
    </nav>
    {children}
    </body>
    </html>
  );
}
